services:
  apache-shardingsphere-proxy:
    image: localhost:22345/testbloodline/apache-shardingsphere-proxy:5.5.1-SNAPSHOT
    restart: always
    environment:
      TZ: Asia/Shanghai
      PORT: 3308
    ports:
      - "13308:3308"
    volumes:
      - ./conf:/opt/shardingsphere-proxy/conf
