services:
  gitea-server:
    image: gitea/gitea:1.22.1-rootless
    restart: always
    environment:
      SSH_PORT: 12345
      HTTP_PORT: 22345
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "22345:22345"
      - "12345:12345"
    networks:
      - gitea-tier
volumes:
  gitea-data:
  gitea-config:
networks:
  gitea-tier:
